server:
  port: 8080
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
